name: df
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rasterio
  - ipykernel
  - numpy
  - tqdm
  - pyyaml
  - pip:
      - planetary-computer
      - deepforest
      - geopandas
      - datasets
      - torch
      - torchvision
      - pytorch-lightning
      - transformers
      - timm
      - albumentations
      - supervision
      - pystac-client
      - matplotlib
      - scikit-learn
      - opencv-python
      - pandas
      - shapely
      - hydra-core
      - tensorboard
      - requests
      - python-dotenv